module CalcApp
{
	interface Calc //Interfaz de comunicacion entre cliente y servidor
	{
		exception DivisionByZero {};

		float sum(in float a, in float b);
		float div(in float a, in float b) raises (DivisionByZero);
		float mul(in float a, in float b);
		float sub(in float a, in float b);
		float decimalABinario(in float a); //Se ha anadido la nueva funcionalidad
	};
};
